[project]
name = "simple-mcp-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.5.2",
    "mcp[cli]>=1.9.2",
    "smolagents[mcp,toolkit]>=1.17.0",
]
